version: "3.8"

networks:
  default:
    external: true
    name: ergo-node

volumes:
  ergo_node:
    external: true

services:
  # Ergo blockchain node
  node:
    image: ergoplatform/ergo:v4.0.105
    container_name: ergo-node
    command: --mainnet -c /etc/ergo.conf
    volumes:
      - ergo_node:/home/ergo/.ergo
      - ./ergo.conf:/etc/ergo.conf:ro
    ports:
      - "9053:9053"
      - "9030:9030"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "6g"
    environment:
      - _JAVA_OPTIONS=-Xms4G -Xmx4G # HEAP: same values for best performance
    logging:
      options:
        max-size: "10m"
        max-file: "3"
